# Starship prompt integration for ccusage-byobu
# Add these sections to your ~/.config/starship.toml file

# Basic Claude usage display
[custom.claude_usage]
command = "ccusage-byobu 2>/dev/null"
when = "command -v ccusage-byobu >/dev/null"
format = "[$output]($style) "
style = "bold blue"
description = "Claude Code usage metrics"

# Advanced integration with conditional display
[custom.claude_active]
command = '''
output=$(ccusage-byobu 2>/dev/null)
if [ -n "$output" ]; then
    echo "🤖 $output"
fi
'''
when = "ccusage blocks --json --offline 2>/dev/null | grep -q '\"isActive\":true'"
format = "[$output]($style) "
style = "bold cyan"
description = "Claude Code active session"

# Colored display based on usage level
[custom.claude_status]
command = '''
output=$(ccusage-byobu 2>/dev/null)
if [ -n "$output" ]; then
    # Extract percentage from progress bar if present
    if echo "$output" | grep -q "█"; then
        filled=$(echo "$output" | grep -o "█" | wc -l)
        if [ "$filled" -ge 8 ]; then
            echo "🔴 $output"
        elif [ "$filled" -ge 6 ]; then
            echo "🟡 $output"
        else
            echo "🟢 $output"
        fi
    else
        echo "⚡ $output"
    fi
fi
'''
when = "command -v ccusage-byobu >/dev/null"
format = "[$output](bold white) "
description = "Claude Code usage with status indicators"

# Minimal integration for compact prompts
[custom.claude_compact]
command = "ccusage-byobu 2>/dev/null | sed 's/\\[.*\\] //'"
when = "ccusage blocks --json --offline 2>/dev/null | grep -q '\"isActive\":true'"
format = "Claude: [$output](dim blue) "
description = "Compact Claude usage display"